### ISSUE TITLE
Remove it 

### ISSUE THREAD

**Issue by therboy** [icebarf/perfmode#10]
i installed the app via GitHub (not aur)
now i need remove it but pacman -R perfmode not working ,,,
the reason i need to remove it is fn+f10 not working but before installing perfmode it was working 
fn + f10 must disable/enable touch pad 
can you help me pls ? 
how to remove perfmode or how to enable fn+f10 again

**Comment by icebarf** [comment]
`rm /usr/bin/perfmode` to remove the binary

Perfmode shouldn't interfere with anything on your system, it just writes to a file exposed by the kernel. Seems you might be facing this issue due to other things. 
Check BIOS and see if your touchpad gets detected or not. Remember that Asus Tuf FX505 has had touchpad issues in general as well.

**Comment by icebarf** [comment]
Closing because no response from the user

**Comment by therboy** [comment]
> `rm /usr/bin/perfmode` to remove the binary
> 
> Perfmode shouldn't interfere with anything on your system, it just writes to a file exposed by the kernel. Seems you might be facing this issue due to other things. Check BIOS and see if your touchpad gets detected or not. Remember that Asus Tuf FX505 has had touchpad issues in general as well.

Thank you for your response! I apologize for my late reply. I found that the issue was caused by some personal scripts I had running, which somehow interfered with the kernel. Once I addressed that, everything started working fine.

I appreciate your help!
Best regards,
your fan
